[package]
name = "hikaru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
indoc = "2.0.4"
lazy_static = "1.4.0"
rand = "0.8.5"
rayon = "1.8.0"
regex = "1.10.2"
